# Generated by Django 4.0.3 on 2022-05-23 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('l_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('r_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('driver_type', models.CharField(choices=[('OO', 'Owner operator'), ('CD', 'Company driver'), ('LO', 'Lease operator')], max_length=2)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, max_digits=9)),
                ('budget_type', models.CharField(choices=[('D', 'driver'), ('L', 'lane'), ('R', 'recovery')], max_length=1)),
                ('bol_number', models.CharField(max_length=15)),
                ('pcs_number', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.driver')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
