# Generated by Django 4.0.3 on 2022-04-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('l_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('r_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher', to=settings.AUTH_USER_MODEL)),
                ('uptader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
