# Generated by Django 4.0.1 on 2022-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bol_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
