# Generated by Django 4.0.3 on 2022-04-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_driver_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='uptader',
            new_name='updater',
        ),
    ]
