# Generated by Django 4.0.3 on 2022-04-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_driver_dispatcher_alter_driver_updater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, max_digits=9)),
                ('budget_type', models.CharField(max_length=1)),
                ('bol_number', models.CharField(max_length=15)),
                ('pcs_number', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.driver')),
            ],
        ),
    ]
