# Generated by Django 4.0.1 on 2022-07-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_driver_s_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LogEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('original_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.log')),
            ],
        ),
    ]
