# Generated by Django 4.0.1 on 2022-07-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_log_is_edited_logedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='logedit',
            name='edited_log',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='edited', to='budget.log'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logedit',
            name='original_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='budget.log'),
        ),
    ]
