# Generated by Django 4.0.3 on 2022-04-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='budget_type',
            field=models.CharField(choices=[('D', 'driver'), ('L', 'lane'), ('R', 'recovery')], max_length=1),
        ),
    ]
