# Generated by Django 4.0.3 on 2022-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_log_budget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
