# Generated by Django 4.0.4 on 2022-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_logedit_edited_log_alter_logedit_original_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_type',
            field=models.CharField(choices=[('OO', 'Owner operator'), ('CD', 'Company driver'), ('LO', 'Lease operator')], max_length=3),
        ),
    ]
