# Generated by Django 4.0.3 on 2022-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
