# Generated by Django 4.0.3 on 2022-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
