# Generated by Django 4.0.3 on 2022-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_log_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dr_type',
            field=models.CharField(choices=[('OO', 'Owner operator'), ('CD', 'Company driver'), ('LO', 'Lease operator')], default='LO', max_length=2),
            preserve_default=False,
        ),
    ]
