# Generated by Django 4.0.3 on 2022-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_driver_dr_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='dr_type',
            new_name='driver_type',
        ),
    ]
