# Generated by Django 4.0.4 on 2022-08-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_driver_gross'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='gross',
            new_name='gross_target',
        ),
    ]
