# Generated by Django 4.0.4 on 2022-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rename_gross_driver_gross_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='total_miles',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='gross_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000.0, max_digits=9, null=True),
        ),
    ]
