# Generated by Django 4.0.4 on 2022-08-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0012_log_total_miles_alter_driver_gross_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dispatcher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
