# Generated by Django 4.0.3 on 2022-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_staff_staff_driver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='1', max_length=12),
            preserve_default=False,
        ),
    ]
