# Generated by Django 4.0.4 on 2022-08-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_driver_dispatcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
