# Generated by Django 4.0.3 on 2022-05-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_staff_driver_group_staff_delete_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='dispatcher',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updater',
        ),
    ]
