# Generated by Django 4.1.1 on 2022-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bol_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
