# Generated by Django 4.0.4 on 2022-07-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=12, unique=True)),
                ('trailer_type', models.CharField(choices=[('c', 'Company'), ('r', 'Ryder'), ('l', 'Lease'), ('o', 'Other')], default='c', max_length=1)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.BinaryField(choices=[(1, 'Pick Up'), (0, 'Drop')], default=0, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailers.trailer')),
            ],
        ),
    ]
