# Generated by Django 4.0.4 on 2022-07-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.BinaryField(choices=[(1, 'Pick Up'), (0, 'Drop')], null=True),
        ),
    ]
