# Generated by Django 4.0.4 on 2022-07-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('trailers', '0002_trailer_is_active_alter_log_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
        migrations.AddField(
            model_name='log',
            name='other_driver',
            field=models.BooleanField(default=0),
        ),
    ]
