# Generated by Django 4.0.4 on 2022-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0003_log_driver_log_other_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.BinaryField(choices=[(1, 'Hook'), (0, 'Drop')], null=True),
        ),
    ]
