# Generated by Django 4.0.4 on 2022-07-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('driver_type', models.CharField(choices=[('OO', 'Owner operator'), ('CD', 'Company driver'), ('LO', 'Lease operator')], max_length=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
    ]
